version: "3"
services:
  bb-sku-catalog-api-php-client:
    image: europe-docker.pkg.dev/dk-gg-rgstry/base/php:dev
    container_name: bb_sku_catalog_api_php_client
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "30290:3000"
