version: "3"
services:
  bb-sku-catalog-api-php-client:
    image: europe-docker.pkg.dev/dk-gg-rgstry/base/php:dev-linux
    container_name: bb_sku_catalog_api_php_client
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "30290:3000"
    environment:
      VALID_TOKEN_SKU_GET: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI5MzQ5OGZhMy1hMDI5LTQ3NGUtODNlYy1iM2ZjZjIyYzhjZGYiLCJqdGkiOiI5YmVlNmM1ZGEzM2UyMDRmYTY4OTYxMDQ0YzQzMDljNTI1Nzk4OTE1MDM5M2Y1ZDkwNmE3ODRkNWYzMjgzZDc2NjM0ZDYyNzZkNmZiNTVmZSIsImlhdCI6MTYxOTUxMzE1Ni41Nzk1MjksImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMjUwIiwibmJmIjoxNjE5NTEzMTU2LjU3OTUyOSwiZXhwIjo0Nzc1MTg2NzU2LjU3OTUyOSwic3ViIjoiIiwic2NvcGVzIjpbInNrdTpnZXQiXX0.iMYZiFI3vbhcAKRYaBoGSo_iE76wO4TiV3lqvrj8heBSnZ5DP5sy7SxLUbp1-8N1Gq1Cv7pfGpUOLDIwhQUC8g
      VALID_TOKEN_SKU_ADD: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI5MzQ5OGZhMy1hMDI5LTQ3NGUtODNlYy1iM2ZjZjIyYzhjZGYiLCJqdGkiOiIzZDFiNGEzZjlhMmFjOGMyNzA0ZTc3MDYzNzZjMzNkMzU2OTg3YTBiYjJkM2QxNDFhMjI0YjUyZDkxOTA4YTAwYWQzMzU0YmJjYzE2ZThmMyIsImlhdCI6MTYxOTUxMzEwOS4zNzg2NDcsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMjUwIiwibmJmIjoxNjE5NTEzMTA5LjM3ODY0NywiZXhwIjo0Nzc1MTg2NzA5LjM3ODY0Nywic3ViIjoiIiwic2NvcGVzIjpbInNrdTphZGQiXX0.oWRR5GcJHls9qNyibm9K8rJTc5ws367yNEUhu_RnMOrPI_6OUVua0fvAZfJFY4XiX3yN7LUlLBkID9vQ2WYHUQ
      VALID_TOKEN_SKU_GROUP_ADD: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI5MzQ5OGZhMy1hMDI5LTQ3NGUtODNlYy1iM2ZjZjIyYzhjZGYiLCJqdGkiOiIzYTlmZjg2NWIxYzI4NTQzNzc0ZTE5MTZkYjRmMWY4MDZhZGNhMThhYWE5MTNhMWQxOTFlNzdlMTUyMjdjNGYxYjBmNmM2NjgxMGQ4MjE0YSIsImlhdCI6MTYxOTUxMzIxMy41NzE5ODYsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMjUwIiwibmJmIjoxNjE5NTEzMjEzLjU3MTk4NiwiZXhwIjo0Nzc1MTg2ODEzLjU3MTk4Niwic3ViIjoiIiwic2NvcGVzIjpbInNrdS1ncm91cDphZGQiXX0.p2U1koSwnwIW2aW1-jXpt7JK5zZM1PIr7R6a14TAVT-WtAvi822HxokvmIjkGnlYqRG8Izn64KBVY3srrEBbmQ
      VALID_TOKEN_SKU_GROUP_GET: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhdWQiOiI5MzQ5OGZhMy1hMDI5LTQ3NGUtODNlYy1iM2ZjZjIyYzhjZGYiLCJqdGkiOiJlZTIxZmVmMzI5ZTRjM2JmNzA4ZGVmNjNhMDdiOGI3NjVlOTkwNjg1ZWRhYjFmNjNhM2U5ODEyZjgyNDNjMGNlOTlkNDdmM2NlOTM3M2NhNCIsImlhdCI6MTYxOTUxMzE4OC4yNjk4MTQsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjMwMjUwIiwibmJmIjoxNjE5NTEzMTg4LjI2OTgxNCwiZXhwIjo0Nzc1MTg2Nzg4LjI2OTgxNCwic3ViIjoiIiwic2NvcGVzIjpbInNrdS1ncm91cDpnZXQiXX0.auL45fCUKX1tsnYrESMr-sDZn0kqC-xk_4kH3Z03-xfgI7z78CvxcQbj6vUHf2b5CwnWt7TFkPC4T2UqLab_EQ
  bb-sku-catalog-api-php-client-pact-mock-service:
    image: pactfoundation/pact-cli
    container_name: bb_sku_catalog_api_php_client_pact_mock_service
    volumes:
      - ./pacts/:/pacts
    ports:
      - "30297:30297"
    command: [
        "mock-service",
        "--port", "30297",
        "--host", "0.0.0.0",
        "--pact-file-write-mode", "overwrite",
        "--consumer", "skuCatalogConsumer",
        "--provider", "skuCatalogProvider",
        "--pact-dir", "/pacts"
    ]