version: "3"
services:
  bb-sku-catalog-api-php-client:
    image: europe-docker.pkg.dev/dk-gg-rgstry/base/php:dev-linux
    container_name: bb_sku_catalog_api_php_client
    volumes:
      - ./:/var/www
    working_dir: /var/www
    ports:
      - "30290:3000"
  pact-mock-service:
    image: pactfoundation/pact-cli
    container_name: pact-mock-service
    volumes:
      - ./pacts/:/pacts
    ports:
      - "7935:7935"
    command: "mock-service --port 7935 --host 0.0.0.0 --pact-file-write-mode=overwrite --consumer=skuCatalogConsumer --provider=skuCatalogProvider --pact-dir /pacts"